# Generated by Django 3.2.6 on 2021-08-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_card', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('surnames', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('photo', models.ImageField(upload_to='persons/')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('type_of_license', models.CharField(max_length=255)),
                ('license_issue_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_card', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('surnames', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('photo', models.ImageField(upload_to='persons/')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(max_length=255)),
                ('accumulated_miles', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
